# Generated by Django 6.0.4 on 2026-04-11 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempt', models.CharField(max_length=150)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failed', 'Xato parol'), ('blocked', 'Bloklangan')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login log',
                'verbose_name_plural': 'Login loglar',
                'ordering': ['-created_at'],
            },
        ),
    ]
