# Generated by Django 4.2.29 on 2026-09-09 08:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_ip_loginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[users.models.validate_phone]),
        ),
    ]
