# Generated by Django 4.2.29 on 2026-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='MCQ uchun: [{"key": "A", "text": "..."}, ...]'),
        ),
    ]
