# Generated by Django 4.2.29 on 2026-04-17 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='word_limit',
            field=models.IntegerField(default=0, help_text="Writing task uchun minimum so'z soni (0 = chegarasiz)"),
        ),
        migrations.AddField(
            model_name='section',
            name='duration_minutes',
            field=models.IntegerField(default=0, help_text='0 = umumiy exam vaqtidan foydalaniladi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tfng', 'True/False/Not Given'), ('gap_fill', 'Gap Fill'), ('matching', 'Matching'), ('writing_task', 'Writing Task (Essay)'), ('short_answer', 'Short Answer')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.userresult')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi javobi',
                'verbose_name_plural': 'Foydalanuvchi javoblari',
                'unique_together': {('result', 'question')},
            },
        ),
    ]
