# Generated by Django 4.2.29 on 2026-04-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_question_word_limit_section_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='writing_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
