# Generated by Django 4.2.29 on 2026-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_writing_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='speaking_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
