# Generated by Django 4.2.29 on 2026-04-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_speaking_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ai_metadata',
            field=models.JSONField(blank=True, help_text='AI generation params: variant, topic, model', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
