# Generated by Django 4.2.29 on 2026-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_ai_generated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model_answer',
            field=models.TextField(blank=True, help_text='Ideal response for Writing/Speaking'),
        ),
        migrations.AddField(
            model_name='section',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Vocabulary, etc.', null=True),
        ),
    ]
