# Generated by Django 4.2.29 on 2026-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_question_model_answer_section_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exams/images/'),
        ),
    ]
