# Generated by Django 4.2.29 on 2026-05-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text="Mutaxassis tomonidan ko'rib chiqilgan"),
        ),
    ]
